# Generated by Django 4.1.3 on 2023-02-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todo', '0006_projects_repository_alter_projects_title_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0002_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
