# Generated by Django 4.1.3 on 2023-02-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
