# Generated by Django 4.1.3 on 2022-12-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_options_remove_todo_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.projects'),
        ),
    ]
