# Generated by Django 4.1.3 on 2023-03-17 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_projects_repository_alter_projects_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='proj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todo.projects'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
