# Generated by Django 4.1.3 on 2023-03-17 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0007_alter_todo_proj_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.projects'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
