# Generated by Django 4.1.3 on 2023-03-17 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0008_alter_todo_proj_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
